export const avengersData = [
  {
    "url": "http://marvel.wikia.com/henry_pym_(earth-616)",
    "name/alias": "henry jonathan \"hank\" pym",
    "appearances": 1269,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-63",
    "year": 1963,
    "years since joining": 52,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "merged with ultron in rage of ultron vol. 1. a funeral was held."
  },
  {
    "url": "http://marvel.wikia.com/janet_van_dyne_(earth-616)",
    "name/alias": "janet van dyne",
    "appearances": 1165,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-63",
    "year": 1963,
    "years since joining": 52,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in secret invasion v1:i8. actually was sent tto microverse later recovered"
  },
  {
    "url": "http://marvel.wikia.com/anthony_stark_(earth-616)",
    "name/alias": "anthony edward \"tony\" stark",
    "appearances": 3068,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-63",
    "year": 1963,
    "years since joining": 52,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "death: \"later while under the influence of immortus stark committed a number of horrible acts and was killed.'  this set up young tony. franklin richards later brought him back"
  },
  {
    "url": "http://marvel.wikia.com/robert_bruce_banner_(earth-616)",
    "name/alias": "robert bruce banner",
    "appearances": 2089,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-63",
    "year": 1963,
    "years since joining": 52,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in ghosts of the future arc. however \"he had actually used a hidden pantheon base to survive"
  },
  {
    "url": "http://marvel.wikia.com/thor_odinson_(earth-616)",
    "name/alias": "thor odinson",
    "appearances": 2402,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-63",
    "year": 1963,
    "years since joining": 52,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "no",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in fear itself brought back because that's kind of the whole point. second death in time runs out has not yet returned"
  },
  {
    "url": "http://marvel.wikia.com/richard_jones_(earth-616)",
    "name/alias": "richard milhouse jones",
    "appearances": 612,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-63",
    "year": 1963,
    "years since joining": 52,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/steven_rogers_(earth-616)",
    "name/alias": "steven rogers",
    "appearances": 3458,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "mar-64",
    "year": 1964,
    "years since joining": 51,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies at the end of civil war. later comes back."
  },
  {
    "url": "http://marvel.wikia.com/clint_barton_(earth-616)",
    "name/alias": "clinton francis barton",
    "appearances": 1456,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "may-65",
    "year": 1965,
    "years since joining": 50,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "yes",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in exploding kree ship in averngers vol. 1  issue 502. brought back by scarlet witch. dies again in house of m vol 1 issue 7. is later brought back."
  },
  {
    "url": "http://marvel.wikia.com/pietro_maximoff_(earth-616)",
    "name/alias": "pietro maximoff",
    "appearances": 769,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "may-65",
    "year": 1965,
    "years since joining": 50,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in house of m vol 1 issue 7. later comes back"
  },
  {
    "url": "http://marvel.wikia.com/wanda_maximoff_(earth-616)",
    "name/alias": "wanda maximoff",
    "appearances": 1214,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "may-65",
    "year": 1965,
    "years since joining": 50,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in uncanny_avengers_vol_1_14. later comes back"
  },
  {
    "url": "http://marvel.wikia.com/jacques_duquesne_(earth-616)",
    "name/alias": "jacques duquesne",
    "appearances": 115,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-65",
    "year": 1965,
    "years since joining": 50,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in avengers_vol_1_130. brought back by the chaos king"
  },
  {
    "url": "http://marvel.wikia.com/hercules_(earth-616)",
    "name/alias": "heracles",
    "appearances": 741,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "oct-67",
    "year": 1967,
    "years since joining": 48,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/t%27challa_(earth-616)",
    "name/alias": "t'challa",
    "appearances": 780,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "may-68",
    "year": 1968,
    "years since joining": 47,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/vision_(earth-616)",
    "name/alias": "victor shade (alias)",
    "appearances": 1036,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "nov-68",
    "year": 1968,
    "years since joining": 47,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in avengers_vol_1_500. is eventually rebuilt."
  },
  {
    "url": "http://marvel.wikia.com/dane_whitman",
    "name/alias": "dane whitman",
    "appearances": 482,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "dec-69",
    "year": 1969,
    "years since joining": 46,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/natalia_romanova_(earth-616)#",
    "name/alias": "natalia alianovna romanova",
    "appearances": 1112,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "may-73",
    "year": 1973,
    "years since joining": 42,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed by the hand. later revived with the stone of the chaste."
  },
  {
    "url": "http://marvel.wikia.com/mantis_(earth-616)#",
    "name/alias": "brandt",
    "appearances": 160,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "aug-73",
    "year": 1973,
    "years since joining": 42,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in silver_surfer_vol_3_3. actually \"fragments of her essence were spread out all across the universe"
  },
  {
    "url": "http://marvel.wikia.com/henry_mccoy_(earth-616)#",
    "name/alias": "henry p. mccoy",
    "appearances": 1886,
    "current?": "no",
    "gender": "male",
    "probationary introl": "jul-75",
    "full/reserve avengers intro": "sep-76",
    "year": 1976,
    "years since joining": 39,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/heather_douglas_(earth-616)#",
    "name/alias": "heather douglas",
    "appearances": 332,
    "current?": "no",
    "gender": "female",
    "probationary introl": "jul-75",
    "full/reserve avengers intro": "sep-76",
    "year": 1976,
    "years since joining": 39,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "yes",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in defenders_vol_1_152. later 'obtained a new body.' dies in annihilation:_conquest_vol_1_3. comes back as \"as before\" also was once named madame macevil because lol."
  },
  {
    "url": "http://marvel.wikia.com/patricia_walker_(earth-616)#",
    "name/alias": "patsy walker",
    "appearances": 557,
    "current?": "no",
    "gender": "female",
    "probationary introl": "nov-75",
    "full/reserve avengers intro": "sep-76",
    "year": 1976,
    "years since joining": 39,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died during time on defenders. eventually ressurected by villian grim reaper along with mockingbird to fight the avengers."
  },
  {
    "url": "http://marvel.wikia.com/matthew_hawk_(earth-616)#",
    "name/alias": "matthew liebowitz (birth name)",
    "appearances": 197,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "aug-75",
    "year": 1975,
    "years since joining": 40,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "no",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died during return_to_the_old_west. resurrected by she hulk in negotiation with time variance authority. as a time traveller he died in 1938. did not return"
  },
  {
    "url": "http://marvel.wikia.com/robert_frank_(earth-616)#",
    "name/alias": "robert l. frank sr.",
    "appearances": 106,
    "current?": "no",
    "gender": "male",
    "probationary introl": "apr-77",
    "full/reserve avengers intro": "jul-78",
    "year": 1978,
    "years since joining": 37,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in vision_and_the_scarlet_witch_vol_1_2. did not return however he was eventually cloned but the clone was killed immediately."
  },
  {
    "url": "http://marvel.wikia.com/simon_williams_(earth-616)#",
    "name/alias": "simon williams",
    "appearances": 692,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "apr-77",
    "full/reserve avengers intro": "mar-79",
    "year": 1979,
    "years since joining": 36,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in avengers_vol_1_9. actually just in a death-like coma."
  },
  {
    "url": "http://marvel.wikia.com/yondu_udonta_(earth-691)#",
    "name/alias": "yondu udonta",
    "appearances": 109,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-78",
    "year": 1978,
    "years since joining": 37,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/martinex_t%27naga_(earth-691)#",
    "name/alias": "martinex t'naga",
    "appearances": 100,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-78",
    "year": 1978,
    "years since joining": 37,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/charlie-27_(earth-691)#",
    "name/alias": "charlie-27",
    "appearances": 132,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-78",
    "year": 1978,
    "years since joining": 37,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/nicholette_gold_(earth-691)#",
    "name/alias": "nicholette gold",
    "appearances": 108,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-78",
    "year": 1978,
    "years since joining": 37,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/stakar_ogord_(earth-691)#",
    "name/alias": "stakar",
    "appearances": 100,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-78",
    "year": 1978,
    "years since joining": 37,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/vance_astro_(earth-691)#",
    "name/alias": "vance astrovik",
    "appearances": 156,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-78",
    "year": 1978,
    "years since joining": 37,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/mar-vell_(earth-616)#",
    "name/alias": "mar-vell",
    "appearances": 254,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-78",
    "year": 1978,
    "years since joining": 37,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "yes",
    "death3": "yes",
    "return3": "no",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "the bad penny of the marvel universe. first killed in secret invasion. revived during the chaos war. died again during aformentioned chaos war. resurrected by the kree empire using them'kraan crystal. third death during avengers vs. x-men. has not return"
  },
  {
    "url": "http://marvel.wikia.com/carol_danvers_(earth-616)#",
    "name/alias": "carol susan jane danvers",
    "appearances": 935,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "apr-79",
    "year": 1979,
    "years since joining": 36,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/samuel_wilson_(earth-616)#",
    "name/alias": "samuel thomas wilson",
    "appearances": 576,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jun-79",
    "year": 1979,
    "years since joining": 36,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/jocasta_(earth-616)#",
    "name/alias": "jocasta",
    "appearances": 141,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "jul-80",
    "full/reserve avengers intro": "nov-88",
    "year": 1988,
    "years since joining": 27,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "yes",
    "death3": "yes",
    "return3": "yes",
    "death4": "yes",
    "return4": "yes",
    "death5": "yes",
    "return5": "yes",
    "notes": "from her article: death1: \"defeated ultron and reversed the process leaving jocasta a mindless husk.\" return 1: \"ultron later revived jocasta with a remote link activating the mental residue the wasp left behind\" death 2: \"sacrificing herself to try to ki"
  },
  {
    "url": "http://marvel.wikia.com/greer_nelson_(earth-616)#",
    "name/alias": "greer grant nelson",
    "appearances": 355,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-81",
    "year": 1981,
    "years since joining": 34,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/jennifer_walters_(earth-616)#",
    "name/alias": "jennifer walters",
    "appearances": 933,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-82",
    "year": 1982,
    "years since joining": 33,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies during red hulk saga. returns when lyra infiltrates intelligenica and finds her in statis"
  },
  {
    "url": "http://marvel.wikia.com/monica_rambeau_(earth-616)#",
    "name/alias": "monica rambeau",
    "appearances": 348,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "jan-83",
    "full/reserve avengers intro": "may-83",
    "year": 1983,
    "years since joining": 32,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/eros_(earth-616)#",
    "name/alias": "eros",
    "appearances": 206,
    "current?": "no",
    "gender": "male",
    "probationary introl": "jun-83",
    "full/reserve avengers intro": "may-84",
    "year": 1984,
    "years since joining": 31,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/james_rhodes_(earth-616)#",
    "name/alias": "james r. rhodes",
    "appearances": 533,
    "current?": "no",
    "gender": "male",
    "probationary introl": "may-84",
    "full/reserve avengers intro": "sep-84",
    "year": 1984,
    "years since joining": 31,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/barbara_morse_(earth-616)#",
    "name/alias": "barbara barton (nee morse)",
    "appearances": 374,
    "current?": "no",
    "gender": "female",
    "probationary introl": "jun-84",
    "full/reserve avengers intro": "sep-84",
    "year": 1984,
    "years since joining": 31,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed by mephisto. after secret invasion it turns out she was actually being impersonated by a skrull the whole time and was alive and well."
  },
  {
    "url": "http://marvel.wikia.com/moira_brandon_(earth-616)#",
    "name/alias": "moira brandon",
    "appearances": 2,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "nov-93",
    "year": 1993,
    "years since joining": 22,
    "honorary": "honorary",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in her second appearance earns honorary avengers status doing so. stays dead."
  },
  {
    "url": "http://marvel.wikia.com/benjamin_grimm_(earth-616)#",
    "name/alias": "benjamin jacob grimm",
    "appearances": 2305,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jun-86",
    "year": 1986,
    "years since joining": 29,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "once killed during a battle with doctor doom.' brought back by the ff when they literally went to heaven to get him."
  },
  {
    "url": "http://marvel.wikia.com/bonita_juarez_(earth-616)#",
    "name/alias": "bonita juarez",
    "appearances": 83,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-87",
    "year": 1987,
    "years since joining": 28,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/marc_spector_(earth-616)#",
    "name/alias": "marc spector",
    "appearances": 402,
    "current?": "no",
    "gender": "male",
    "probationary introl": "sep-87",
    "full/reserve avengers intro": "jun-88",
    "year": 1988,
    "years since joining": 27,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na but he he did die and return to get his powers prior to joining the avengers."
  },
  {
    "url": "http://marvel.wikia.com/john_walker_(earth-616)#",
    "name/alias": "john f. walker",
    "appearances": 352,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "may-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/human_torch_(android)_(earth-616)#",
    "name/alias": "jim hammond (alias)",
    "appearances": 565,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "nov-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies during new invaders. was \"was revived as a living weapon the thinker intended to sell.\" prior to joining the avengers he had died like 2 times in the 40s."
  },
  {
    "url": "http://marvel.wikia.com/miguel_santos_(earth-616)#",
    "name/alias": "miguel santos",
    "appearances": 112,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "apr-91",
    "year": 1991,
    "years since joining": 24,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na: has not died since joing the avengers but prior to joining he fought the west coast avengers and seemingly died. later turned up under control of a villain"
  },
  {
    "url": "http://marvel.wikia.com/julia_carpenter_(earth-616)#",
    "name/alias": "julia carpenter",
    "appearances": 218,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "sep-92",
    "year": 1992,
    "years since joining": 23,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/2zp45-9-x-51_(earth-616)#",
    "name/alias": "x-51",
    "appearances": 149,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jun-92",
    "year": 1992,
    "years since joining": 23,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in deathlok vol 2 #5. jk that was actually just a life model decoy"
  },
  {
    "url": "http://marvel.wikia.com/chris_powell_(earth-616)#",
    "name/alias": "christopher powell",
    "appearances": 168,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "may-93",
    "year": 1993,
    "years since joining": 22,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/namor_mckenzie_(earth-616)#",
    "name/alias": "namor mckenzie",
    "appearances": 1561,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "dec-85",
    "year": 1985,
    "years since joining": 30,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "namor was presumed killed in the battle with atlantean barbarians. had actually survived and turned up in the south pacific"
  },
  {
    "url": "http://marvel.wikia.com/scott_lang_(earth-616)#",
    "name/alias": "scott edward harris lang",
    "appearances": 217,
    "current?": "no",
    "gender": "male",
    "probationary introl": "jan-87",
    "full/reserve avengers intro": "3-feb",
    "year": 2003,
    "years since joining": 12,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in avengers:_disassembled. was brought back in the young avengers: children's crusade arc because time travel but take my word for it it was actually kind of well done."
  },
  {
    "url": "http://marvel.wikia.com/anthony_druid_(earth-616)#",
    "name/alias": "anthony ludgate druid",
    "appearances": 158,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "apr-87",
    "year": 1987,
    "years since joining": 28,
    "honorary": "honorary",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "yes",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "shot with a breathing gun and corpse dumped in trash. revived by the grim reaper. helped avengers defeat the reaper so his spirit could remain at peace. later completely revived by the chaos king."
  },
  {
    "url": "http://marvel.wikia.com/marrina_smallwood_(earth-616)#",
    "name/alias": "marrina smallwood",
    "appearances": 86,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "dec-87",
    "year": 1987,
    "years since joining": 28,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "yes",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed by namor with the ebony blade. returned when the master put her in a statis tube. death 2 was when namor mercy killed her. returned to life a second time by the chaos king."
  },
  {
    "url": "http://marvel.wikia.com/ravonna_renslayer_(earth-6311)#",
    "name/alias": "ravonna lexus renslayer",
    "appearances": 41,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "may-88",
    "year": 1988,
    "years since joining": 27,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "no",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed in avengers_vol_1_24. revived by the grandmaster. died in avengers:_forever_vol_1_3."
  },
  {
    "url": "http://marvel.wikia.com/rita_demara_(earth-616)#",
    "name/alias": "rita demara",
    "appearances": 68,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "nov-88",
    "year": 1988,
    "years since joining": 27,
    "honorary": "honorary",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed by iron man when he was controlled by immortus. revived during chaos war."
  },
  {
    "url": "http://marvel.wikia.com/dennis_dunphy_(earth-616)#",
    "name/alias": "dennis dunphy",
    "appearances": 70,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jan-88",
    "year": 1988,
    "years since joining": 27,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "no",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in captain_america_348. actually \"dunphy miraculously survived the crash and lived with an inuit tribe.\" second death when killed by sharon carter."
  },
  {
    "url": "http://marvel.wikia.com/gilgamesh_(earth-616)#",
    "name/alias": "",
    "appearances": 61,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed by neut who was working for immortus. reborn into a new body."
  },
  {
    "url": "http://marvel.wikia.com/reed_richards_(earth-616)#",
    "name/alias": "reed richards",
    "appearances": 2125,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/susan_storm_(earth-616)#",
    "name/alias": "susan richards (nee storm)",
    "appearances": 1761,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/wendell_vaughn_(earth-616)#",
    "name/alias": "wendell elvis vaughn",
    "appearances": 293,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "oct-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed by the cosmic assassin. actually turned into a being composed of pure energy."
  },
  {
    "url": "http://marvel.wikia.com/ashley_crawford_(earth-616)#",
    "name/alias": "ashley crawford",
    "appearances": 36,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/dinah_soar_(earth-616)#",
    "name/alias": "",
    "appearances": 22,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in great_lakes_avengers_vol_1_1. has not returned"
  },
  {
    "url": "http://marvel.wikia.com/demarr_davis_(earth-616)#",
    "name/alias": "demarr davis",
    "appearances": 31,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "sacrificed self so that mr. immortal could stop the villain maelstrom. returned as the angel of death."
  },
  {
    "url": "http://marvel.wikia.com/val_ventura_(earth-616)#",
    "name/alias": "val ventura",
    "appearances": 34,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/craig_hollis_(earth-616)#",
    "name/alias": "craig hollis",
    "appearances": 33,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-89",
    "year": 1989,
    "years since joining": 26,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "christ; where to begin. his superpower is that he cannot die when he dies he immediately comes back. the wikia inventories 24 deaths. these will be excluded from the analysis."
  },
  {
    "url": "http://marvel.wikia.com/gene_lorrene_(earth-616)#",
    "name/alias": "gene lorrene",
    "appearances": 4,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-apr",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/doreen_green_(earth-616)#",
    "name/alias": "dorreen green",
    "appearances": 47,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "5-may",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/monkey_joe_(earth-616)#",
    "name/alias": "",
    "appearances": 7,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-may",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed by leather boy"
  },
  {
    "url": "http://marvel.wikia.com/doug_taggert_(earth-616)#",
    "name/alias": "doug taggert",
    "appearances": 3,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-may",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "accidently killed by zaran"
  },
  {
    "url": "http://marvel.wikia.com/tippy-toe_(earth-616)#",
    "name/alias": "",
    "appearances": 16,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "5-jul",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/wade_wilson_(earth-616)#",
    "name/alias": "wade wilson",
    "appearances": 575,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "7-sep",
    "year": 2007,
    "years since joining": 8,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died during incursion. it's not ever particulalry clear if he ever joined an avengers team besides one issue so his inclusion here is specious at best."
  },
  {
    "url": "http://marvel.wikia.com/greg_willis_(earth-616)#",
    "name/alias": "greg willis",
    "appearances": 58,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "9-aug",
    "year": 2009,
    "years since joining": 6,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died on battleworld and came back prior to joining avengers"
  },
  {
    "url": "http://marvel.wikia.com/sersi_(earth-616)#",
    "name/alias": "circe",
    "appearances": 237,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-90",
    "year": 1990,
    "years since joining": 25,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/peter_parker_(earth-616)#",
    "name/alias": "peter benjamin parker",
    "appearances": 4333,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "apr-90",
    "year": 1990,
    "years since joining": 25,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "yes",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "since joining the new avengers: first death killed by morlun. ressurected in a brand new body. died in amazing spider-man #700. eventually mainfested in his body that octavious stole and then took over again."
  },
  {
    "url": "http://marvel.wikia.com/walter_newell_(earth-616)#",
    "name/alias": "walter newell",
    "appearances": 126,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-90",
    "year": 1990,
    "years since joining": 25,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/elvin_haliday_(earth-616)#",
    "name/alias": "elvin haliday",
    "appearances": 158,
    "current?": "no",
    "gender": "male",
    "probationary introl": "feb-91",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "probationary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/william_baker_(earth-616)#",
    "name/alias": "william baker",
    "appearances": 355,
    "current?": "no",
    "gender": "male",
    "probationary introl": "feb-91",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "probationary",
    "death1": "yes",
    "return1": "yes",
    "death2": "no",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in identity_disc_vol_1_1. later was revealed to be alive and working along with the vulture."
  },
  {
    "url": "http://marvel.wikia.com/crystalia_amaquelin_(earth-616)#",
    "name/alias": "crystal amaquelin maximoff",
    "appearances": 517,
    "current?": "no",
    "gender": "female",
    "probationary introl": "aug-91",
    "full/reserve avengers intro": "jan-92",
    "year": 1992,
    "years since joining": 23,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/eric_masterson_(earth-616)#",
    "name/alias": "eric kevin masterson",
    "appearances": 202,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "jan-92",
    "year": 1992,
    "years since joining": 23,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "no",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "became posessed died to purge self of corruption. revived as undead avenger minion of the grim reaper. returned to the spirit world by the scarlet witch. has since stayed dead."
  },
  {
    "url": "http://marvel.wikia.com/philip_javert_(earth-921)#",
    "name/alias": "phillip javert",
    "appearances": 31,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "dec-92",
    "year": 1992,
    "years since joining": 23,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/melissa_darrow_(earth-9201)#",
    "name/alias": "",
    "appearances": 28,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "jun-93",
    "year": 1993,
    "years since joining": 22,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/deathcry_(earth-616)#",
    "name/alias": "",
    "appearances": 50,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-93",
    "year": 1993,
    "years since joining": 22,
    "honorary": "honorary",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "no",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "reduced her to a pile of bones and organsby vargas. brought back by chaos king. died second time in chaos_war:_dead_avengers_vol_1_3"
  },
  {
    "url": "http://marvel.wikia.com/anthony_stark_(earth-96020)#",
    "name/alias": "anthony edward stark",
    "appearances": 27,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "feb-96",
    "year": 1996,
    "years since joining": 19,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "merged with 616 tony stark"
  },
  {
    "url": "http://marvel.wikia.com/giuletta_nefaria_(masque)_(earth-616)#",
    "name/alias": "giulietta nefaria",
    "appearances": 18,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "apr-96",
    "year": 1996,
    "years since joining": 19,
    "honorary": "honorary",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "whitney killed was a clone possibly this incarnation of masque'"
  },
  {
    "url": "http://marvel.wikia.com/vance_astrovik_(earth-616)#",
    "name/alias": "vance astrovik",
    "appearances": 302,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "may-98",
    "year": 1998,
    "years since joining": 17,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/angelica_jones_(earth-616)#",
    "name/alias": "angelica jones",
    "appearances": 330,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "may-98",
    "year": 1998,
    "years since joining": 17,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/delroy_garrett_jr._(earth-616)#",
    "name/alias": "delroy garrett jr.",
    "appearances": 101,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "apr-00",
    "year": 2000,
    "years since joining": 15,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/maria_de_guadalupe_santiago_(earth-616)#",
    "name/alias": "maria de guadalupe santiago",
    "appearances": 43,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "jul-00",
    "year": 2000,
    "years since joining": 15,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/jonathan_hart_(earth-616)#",
    "name/alias": "jonathan hart",
    "appearances": 126,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "1-aug",
    "year": 2001,
    "years since joining": 14,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "yes",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "first died in a zero energy explosion in space. body was apparently reanimated by scarlet witch. abruptly exploded killing scott lang as well. second return in marvel_zombies_supreme_vol_1_2."
  },
  {
    "url": "http://marvel.wikia.com/kelsey_leigh_(earth-616)#",
    "name/alias": "kelsey leigh shorr",
    "appearances": 24,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "4-jun",
    "year": 2004,
    "years since joining": 11,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/luke_cage_(earth-616)#",
    "name/alias": "carl lucas",
    "appearances": 886,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-mar",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/veranke_(earth-616)#",
    "name/alias": "veranke",
    "appearances": 159,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "5-mar",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "killed by norman osbourne. has not returned."
  },
  {
    "url": "http://marvel.wikia.com/james_howlett_(earth-616)#",
    "name/alias": "james \"logan\" howlett",
    "appearances": 3130,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-jun",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in death_of_wolverine_vol_1_4. has not yet returned"
  },
  {
    "url": "http://marvel.wikia.com/robert_reynolds_(earth-616)#",
    "name/alias": "robert reynolds",
    "appearances": 241,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-oct",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died during seige. brought back to life by the apocalypse twins as a horseman of death in uncanny_avengers_vol_1_9."
  },
  {
    "url": "http://marvel.wikia.com/maya_lopez_(earth-616)#",
    "name/alias": "maya lopez",
    "appearances": 67,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "5-nov",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "no",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "first death 'had been murdered in a fight with elektra.' \"revived by elektra and the hand with their dark magic.\" died in most recent run of moon knight has not yet returned."
  },
  {
    "url": "http://marvel.wikia.com/nathaniel_richards_(iron_lad)_(earth-6311)#",
    "name/alias": "nathaniel richards",
    "appearances": 23,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-apr",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na is actually kang but let's just not go there."
  },
  {
    "url": "http://marvel.wikia.com/elijah_bradley_(earth-616)#",
    "name/alias": "elijah bradley",
    "appearances": 103,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-apr",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/william_kaplan_(earth-616)#",
    "name/alias": "william \"billy\" kaplan",
    "appearances": 123,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-apr",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/dorrek_viii_(earth-616)#",
    "name/alias": "dorrek viii/theodore \"teddy\" altman",
    "appearances": 110,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "5-apr",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/cassandra_lang_(earth-616)#",
    "name/alias": "cassie lang",
    "appearances": 160,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "5-jun",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in young avengers: the childrens crusade when she is killed by doom. eventually reborn years later."
  },
  {
    "url": "http://marvel.wikia.com/katherine_bishop_(earth-616)#",
    "name/alias": "katherine \"kate\" bishop",
    "appearances": 132,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "5-jun",
    "year": 2005,
    "years since joining": 10,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/vision_(jonas)_(earth-616)#",
    "name/alias": "alias: jonas",
    "appearances": 121,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "6-feb",
    "year": 2006,
    "years since joining": 9,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "dies in young avengers the children's crusade"
  },
  {
    "url": "http://marvel.wikia.com/thomas_shepherd_(earth-616)#",
    "name/alias": "thomas \"tommy\" shepherd",
    "appearances": 59,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "6-jun",
    "year": 2006,
    "years since joining": 9,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/daniel_rand_(earth-616)#",
    "name/alias": "daniel thomas rand k'ai",
    "appearances": 629,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "7-feb",
    "year": 2007,
    "years since joining": 8,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/stephen_strange_(earth-616)#",
    "name/alias": "doctor stephen vincent strange",
    "appearances": 1324,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "7-feb",
    "year": 2007,
    "years since joining": 8,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/ares_(earth-616)#",
    "name/alias": "ares",
    "appearances": 236,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "7-mar",
    "year": 2007,
    "years since joining": 8,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "yes",
    "return2": "no",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "ripped in half by the sentry during seige. revived during chaos king. then killedby chaos king."
  },
  {
    "url": "http://marvel.wikia.com/james_buchanan_barnes_(earth-616)#",
    "name/alias": "james buchanan barnes",
    "appearances": 663,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "8-dec",
    "year": 2008,
    "years since joining": 7,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/jessica_drew_(earth-616)#",
    "name/alias": "jessica miriam drew",
    "appearances": 525,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "8-dec",
    "year": 2008,
    "years since joining": 7,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/jessica_jones_(earth-616)#",
    "name/alias": "jessica jones",
    "appearances": 205,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "10-aug",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/amadeus_cho_(earth-616)#",
    "name/alias": "amadeus cho",
    "appearances": 108,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "9-dec",
    "year": 2009,
    "years since joining": 6,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/maria_hill_(earth-616)#",
    "name/alias": "maria hill",
    "appearances": 359,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "10-may",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/robert_baldwin_(earth-616)#",
    "name/alias": "robbie baldwin",
    "appearances": 299,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-jun",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/sharon_carter_(earth-616)#",
    "name/alias": "sharon carter",
    "appearances": 333,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "10-may",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in captain_america_vol_7_10. it's not clear how she survived but yeah she totally did."
  },
  {
    "url": "http://marvel.wikia.com/eric_o%27grady_(earth-616)#",
    "name/alias": "eric o'grady",
    "appearances": 88,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-may",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in secret_avengers_vol_1_22."
  },
  {
    "url": "http://marvel.wikia.com/brunnhilde_(earth-616)#",
    "name/alias": "brunnhilde",
    "appearances": 369,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "10-may",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na but died/came back during ragnarok prior to becoming an avenger"
  },
  {
    "url": "http://marvel.wikia.com/richard_rider_(earth-616)#",
    "name/alias": "richard rider",
    "appearances": 380,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-may",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in guardians_of_the_galaxy_vol_3_20."
  },
  {
    "url": "http://marvel.wikia.com/brian_braddock_(earth-616)#",
    "name/alias": "brian braddock",
    "appearances": 545,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-may",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/dennis_sykes_(earth-616)#",
    "name/alias": "dennis sykes",
    "appearances": 6,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-sep",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in heroic_age:_one_month_to_live_vol_1_5 stayed dead."
  },
  {
    "url": "http://marvel.wikia.com/noh-varr_(earth-616)#",
    "name/alias": "noh-varr",
    "appearances": 126,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-jun",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/thaddeus_ross_(earth-616)#",
    "name/alias": "thaddeus ross",
    "appearances": 417,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "11-jun",
    "year": 2011,
    "years since joining": 4,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in circle of four arc. made a deal with mephisto and came back."
  },
  {
    "url": "http://marvel.wikia.com/john_aman_(earth-616)#",
    "name/alias": "john aman",
    "appearances": 31,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-dec",
    "year": 2010,
    "years since joining": 5,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/shang-chi_(earth-616)#",
    "name/alias": "shang-chi",
    "appearances": 310,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "11-apr",
    "year": 2011,
    "years since joining": 4,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/james_santini_(earth-616)#",
    "name/alias": "james santini",
    "appearances": 40,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/emery_schaub_(earth-616)#",
    "name/alias": "emery schaub",
    "appearances": 26,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/jeanne_foucault_(earth-616)#",
    "name/alias": "jeanne foucault",
    "appearances": 63,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "10-aug",
    "year": 2010,
    "years since joining": 5,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/fiona_(inhuman)_(earth-616)#",
    "name/alias": "fiona",
    "appearances": 2,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/jennifer_takeda_(earth-616)#",
    "name/alias": "jennifer takeda",
    "appearances": 73,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "10-aug",
    "year": 2010,
    "years since joining": 5,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/hollow_(earth-616)#",
    "name/alias": "yvette",
    "appearances": 22,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/julie_power_(earth-616)#",
    "name/alias": "julie power",
    "appearances": 153,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/alani_ryan_(earth-616)#",
    "name/alias": "alani ryan",
    "appearances": 73,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/ken_mack_(earth-616)#",
    "name/alias": "ken mack",
    "appearances": 59,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-aug",
    "year": 2010,
    "years since joining": 5,
    "honorary": "academy",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in murderworld during avengers arena"
  },
  {
    "url": "http://marvel.wikia.com/humberto_lopez_(earth-616)#",
    "name/alias": "humberto lopez",
    "appearances": 66,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-aug",
    "year": 2010,
    "years since joining": 5,
    "honorary": "academy",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in murderworld during avengers arena"
  },
  {
    "url": "http://marvel.wikia.com/johnathon_gallo_(earth-616)#",
    "name/alias": "johnny gallo",
    "appearances": 43,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/lyra_(earth-8009)#",
    "name/alias": "lyra",
    "appearances": 55,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/anya_corazon_(earth-616)#",
    "name/alias": "anya corazon",
    "appearances": 108,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/brandon_sharpe_(earth-616)#",
    "name/alias": "brandon sharpe",
    "appearances": 64,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "10-aug",
    "year": 2010,
    "years since joining": 5,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/kevin_masterson_(earth-616)#",
    "name/alias": "kevin masterson",
    "appearances": 62,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/michiko_musashi_(earth-616)#",
    "name/alias": "michiko musashi",
    "appearances": 94,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/takashi_matsuya_(earth-616)#",
    "name/alias": "taki matsuya",
    "appearances": 18,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "",
    "year": 1900,
    "years since joining": 115,
    "honorary": "academy",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/daisy_johnson_(earth-616)#",
    "name/alias": "daisy johnson",
    "appearances": 81,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "12-jan",
    "year": 2012,
    "years since joining": 3,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/ororo_munroe_(earth-616)#",
    "name/alias": "ororo munroe",
    "appearances": 1598,
    "current?": "no",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "12-jan",
    "year": 2012,
    "years since joining": 3,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/matthew_murdock_(earth-616)#",
    "name/alias": "matt murdock",
    "appearances": 1375,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "11-nov",
    "year": 2011,
    "years since joining": 4,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/eugene_thompson_(earth-616)#",
    "name/alias": "flash thompson",
    "appearances": 746,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "12-apr",
    "year": 2012,
    "years since joining": 3,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/otto_octavius_(earth-616)#",
    "name/alias": "otto octavius",
    "appearances": 561,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-jan",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in superior_spider-man_vol_1_30."
  },
  {
    "url": "http://marvel.wikia.com/alexander_summers_(earth-616)#",
    "name/alias": "alex summers",
    "appearances": 592,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "12-dec",
    "year": 2012,
    "years since joining": 3,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/samuel_guthrie_(earth-616)#",
    "name/alias": "samuel guthrie",
    "appearances": 679,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-feb",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/roberto_da_costa_(earth-616)#",
    "name/alias": "roberto da costa",
    "appearances": 491,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-feb",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/eden_fesi_(earth-616)#",
    "name/alias": "eden fesi",
    "appearances": 65,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-feb",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/captain_universe_(earth-616)#",
    "name/alias": "",
    "appearances": 55,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-feb",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/isabel_kane_(earth-616)#",
    "name/alias": "izzy kane",
    "appearances": 44,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "13-feb",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/marcus_milton_(earth-13034)#",
    "name/alias": "marcus milton",
    "appearances": 65,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-feb",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in new_avengers_vol_3_32."
  },
  {
    "url": "http://marvel.wikia.com/rogue_(anna_marie)_(earth-616)#",
    "name/alias": "anna marie",
    "appearances": 877,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "13-apr",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/shiro_yoshida_(earth-616)#",
    "name/alias": "shiro yoshida",
    "appearances": 176,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-may",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in uncanny_avengers_vol_1_22. returned when 'he was able to use his power to transform his body into a state of pure energy '"
  },
  {
    "url": "http://marvel.wikia.com/ex_nihilo_(earth-616)#",
    "name/alias": "",
    "appearances": 24,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-oct",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in new_avengers_vol_3_32"
  },
  {
    "url": "http://marvel.wikia.com/abyss_(ex_nihilo%27s)_(earth-616)#",
    "name/alias": "",
    "appearances": 25,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "13-oct",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in new_avengers_vol_3_32"
  },
  {
    "url": "http://marvel.wikia.com/nightmask_(earth-616)#",
    "name/alias": "adam",
    "appearances": 35,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-oct",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in new_avengers_vol_3_32"
  },
  {
    "url": "http://marvel.wikia.com/kevin_connor_(earth-616)#",
    "name/alias": "kevin kale connor",
    "appearances": 44,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-oct",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "yes",
    "return1": "no",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in new_avengers_vol_3_32"
  },
  {
    "url": "http://marvel.wikia.com/sam_alexander_(earth-616)#",
    "name/alias": "sam alexander",
    "appearances": 78,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "15-feb",
    "year": 2015,
    "years since joining": 0,
    "honorary": "honorary",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/america_chavez_(earth-616)#",
    "name/alias": "america chavez",
    "appearances": 22,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "13-jul",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/loki_laufeyson_(ikol)_(earth-616)#",
    "name/alias": "loki laufeyson",
    "appearances": 77,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-jul",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/david_alleyne_(earth-616)#",
    "name/alias": "david alleyne",
    "appearances": 115,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-sep",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/nicholas_fury,_jr._(earth-616)#",
    "name/alias": "nicholas fury, jr., marcus johnson",
    "appearances": 77,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-apr",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/phillip_coulson_(earth-616)#",
    "name/alias": "phillip coulson",
    "appearances": 69,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-apr",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/tony_masters_(earth-616)#",
    "name/alias": "tony masters",
    "appearances": 173,
    "current?": "no",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-may",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/victor_mancha_(earth-616)#",
    "name/alias": "victor mancha",
    "appearances": 75,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-sep",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "yes",
    "return1": "yes",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "died in avengers_a.i._vol_1_4. returned in avengers_a.i._vol_1_9."
  },
  {
    "url": "http://marvel.wikia.com/monica_chang_(earth-616)#",
    "name/alias": "monica chang",
    "appearances": 12,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "13-sep",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/doombot_(avenger)_(earth-616)#",
    "name/alias": "",
    "appearances": 14,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-sep",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/alexis_(earth-616)#",
    "name/alias": "alexis",
    "appearances": 13,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "13-nov",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/eric_brooks_(earth-616)#",
    "name/alias": "eric brooks",
    "appearances": 198,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "13-nov",
    "year": 2013,
    "years since joining": 2,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/adam_brashear_(earth-616)#",
    "name/alias": "adam brashear",
    "appearances": 29,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "14-jan",
    "year": 2014,
    "years since joining": 1,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/victor_alvarez_(earth-616)#",
    "name/alias": "victor alvarez",
    "appearances": 45,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "14-jan",
    "year": 2014,
    "years since joining": 1,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/ava_ayala_(earth-616)#",
    "name/alias": "ava ayala",
    "appearances": 49,
    "current?": "yes",
    "gender": "female",
    "probationary introl": "",
    "full/reserve avengers intro": "14-jan",
    "year": 2014,
    "years since joining": 1,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  },
  {
    "url": "http://marvel.wikia.com/kaluu_(earth-616)#",
    "name/alias": "kaluu",
    "appearances": 35,
    "current?": "yes",
    "gender": "male",
    "probationary introl": "",
    "full/reserve avengers intro": "15-jan",
    "year": 2015,
    "years since joining": 0,
    "honorary": "full",
    "death1": "no",
    "return1": "",
    "death2": "",
    "return2": "",
    "death3": "",
    "return3": "",
    "death4": "",
    "return4": "",
    "death5": "",
    "return5": "",
    "notes": "na"
  }
]